# Generated by Django 2.0.3 on 2018-03-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(max_length=50)),
                ('num_vids', models.IntegerField(default=10)),
            ],
        ),
    ]
