# Generated by Django 2.0.3 on 2018-04-05 00:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.CharField(default='', max_length=15, primary_key=True, serialize=False)),
                ('language', models.CharField(default='', max_length=15)),
                ('videos', models.TextField(default='')),
                ('search_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('owner', models.TextField(default='')),
                ('youtube_params', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('num_vids', models.IntegerField(default=10)),
                ('videos', models.TextField(default='')),
                ('channels', models.TextField(default='')),
                ('name', models.TextField(default='')),
                ('query', models.TextField(default='')),
                ('created_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('user_id', models.TextField(default='')),
                ('filters', models.TextField(default='')),
                ('cc_enabled', models.NullBooleanField()),
                ('youtube_params', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.CharField(default='', max_length=15, primary_key=True, serialize=False)),
                ('search_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('videos', models.TextField(default='')),
                ('owner', models.TextField(default='')),
                ('youtube_params', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(default='', max_length=15, primary_key=True, serialize=False)),
                ('channel_id', models.CharField(default='', max_length=15)),
                ('cc_enabled', models.BooleanField()),
                ('transcript_download_success', models.NullBooleanField()),
                ('rating', models.CharField(max_length=100)),
                ('comments', models.TextField(default='')),
                ('language', models.CharField(default='', max_length=15)),
                ('video_def', models.CharField(default='', max_length=15)),
                ('video_duration', models.DurationField(blank=True, null=True)),
                ('search_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('download_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('download_path', models.TextField(default='')),
                ('download_success', models.NullBooleanField()),
                ('mturk_description', models.TextField(default='')),
                ('youtube_params', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('query', models.TextField(default='')),
            ],
        ),
    ]
