# Generated by Django 2.0.3 on 2018-04-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='channel_id',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='job',
            name='ordering',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='job',
            name='safe_search',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='job',
            name='video_def',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='job',
            name='video_duration',
            field=models.CharField(default='', max_length=15),
        ),
    ]
