# Generated by Django 2.0.3 on 2018-07-24 19:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='active_filters',
        ),
        migrations.RemoveField(
            model_name='job',
            name='applied_filters',
        ),
        migrations.RemoveField(
            model_name='job',
            name='channel_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='filtered_videos',
        ),
        migrations.RemoveField(
            model_name='job',
            name='found_channels',
        ),
        migrations.RemoveField(
            model_name='video',
            name='passed_filters',
        ),
        migrations.AddField(
            model_name='job',
            name='region',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='video',
            name='filters',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='job',
            name='filters',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='job',
            name='videos',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='video',
            name='job_ids',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
