# Generated by Django 2.0.7 on 2018-07-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0002_auto_20180725_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='region',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
