# Generated by Django 2.0.3 on 2018-04-05 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0002_auto_20180405_0337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='channels',
            new_name='found_channels',
        ),
    ]
