# Generated by Django 2.0.3 on 2018-03-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0002_job_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('kind', models.TextField(default='')),
                ('etag', models.TextField(default='')),
                ('id', models.TextField(default='', primary_key=True, serialize=False)),
                ('snippet', models.TextField(default='')),
                ('contentDetails', models.TextField(default='')),
                ('statistics', models.TextField(default='')),
                ('topicDetails', models.TextField(default='')),
                ('status', models.TextField(default='')),
                ('brandingSettings', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('kind', models.TextField(default='')),
                ('etag', models.TextField(default='')),
                ('id', models.TextField(default='', primary_key=True, serialize=False)),
                ('snippet', models.TextField(default='')),
                ('contentDetails', models.TextField(default='')),
                ('status', models.TextField(default='')),
                ('statistics', models.TextField(default='')),
                ('player', models.TextField(default='')),
                ('topicDetails', models.TextField(default='')),
                ('localizations', models.TextField(default='')),
            ],
        ),
    ]
