# Generated by Django 2.0.3 on 2018-09-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0002_video_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': [('can_crawl', 'Can Crawl and Download'), ('can_view', 'Can Review the passed videos and answer relevant questions')]},
        ),
        migrations.AddField(
            model_name='job',
            name='failed_status',
            field=models.TextField(default=''),
        ),
    ]
