# Generated by Django 2.0.3 on 2018-07-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0002_auto_20180724_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='channel_id',
            field=models.TextField(default=''),
        ),
    ]
