# Generated by Django 2.0.3 on 2018-07-25 19:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0003_job_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='filters',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='jobs_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
