# Generated by Django 2.0.3 on 2018-04-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0003_auto_20180405_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='executed',
            field=models.BooleanField(default=False),
        ),
    ]
