# Generated by Django 2.0.3 on 2018-04-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0005_auto_20180405_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='channel_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
