# Generated by Django 2.0.3 on 2018-04-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0006_auto_20180405_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cc_enabled',
            field=models.CharField(default='', max_length=50),
        ),
    ]
