# Generated by Django 2.0.3 on 2018-04-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0007_auto_20180405_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cc_enabled',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
