# Generated by Django 2.0.3 on 2018-04-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0008_auto_20180405_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='channel_id',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='comments',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='download_path',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='job_id',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='job_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='language',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='mturk_description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='query',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='rating',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_def',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
