# Generated by Django 2.0.3 on 2018-04-05 05:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0009_auto_20180405_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtube_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True),
        ),
    ]
