# Generated by Django 2.0.3 on 2018-04-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0012_auto_20180405_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='youtube_params',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='youtube_params',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='youtube_params',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_params',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
