# Generated by Django 2.0.3 on 2018-04-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0018_job_num_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
