# Generated by Django 2.0.3 on 2018-04-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0019_job_downloaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='downloaded',
        ),
        migrations.AddField(
            model_name='job',
            name='download_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='download_started',
            field=models.BooleanField(default=False),
        ),
    ]
