# Generated by Django 2.0.3 on 2018-04-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0020_auto_20180413_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='auto_download',
            field=models.BooleanField(default=False),
        ),
    ]
