# Generated by Django 2.0.3 on 2018-04-27 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0021_job_auto_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='auto_download',
        ),
    ]
