# Generated by Django 2.0.3 on 2018-05-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0022_remove_job_auto_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='num_pages',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='num_vids',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
