# Generated by Django 2.0.3 on 2018-06-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0024_dataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='job',
            name='youtube_params',
        ),
    ]
