# Generated by Django 2.0.3 on 2018-06-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0027_auto_20180614_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': [('can_crawl', 'Can Crawl and Download')]},
        ),
        migrations.RemoveField(
            model_name='video',
            name='job_name',
        ),
    ]
