# Generated by Django 2.0.3 on 2018-08-29 21:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='questions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
