# Generated by Django 2.0.3 on 2018-09-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0003_auto_20180909_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='failed_status',
            new_name='work_status',
        ),
    ]
