sudo python align.py ../../MMMO/Main/Raw/Audio/Full/EaKKWq_4zBk.wav ../../MMMO/Main/Raw/Transcript/Full/EaKKWq_4zBk.trs ../../MMMO/Main/Aligned/EaKKWq_4zBk.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/RlThTD5fg8I.wav ../../MMMO/Main/Raw/Transcript/Full/RlThTD5fg8I.trs ../../MMMO/Main/Aligned/RlThTD5fg8I.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/6JH5qz-TLIg.wav ../../MMMO/Main/Raw/Transcript/Full/6JH5qz-TLIg.trs ../../MMMO/Main/Aligned/6JH5qz-TLIg.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/1iG0909rllw.wav ../../MMMO/Main/Raw/Transcript/Full/1iG0909rllw.trs ../../MMMO/Main/Aligned/1iG0909rllw.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/eaX5q8Yn0xI.wav ../../MMMO/Main/Raw/Transcript/Full/eaX5q8Yn0xI.trs ../../MMMO/Main/Aligned/eaX5q8Yn0xI.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/2WGyTLYerpo.wav ../../MMMO/Main/Raw/Transcript/Full/2WGyTLYerpo.trs ../../MMMO/Main/Aligned/2WGyTLYerpo.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/3.wav ../../MMMO/Main/Raw/Transcript/Full/3.trs ../../MMMO/Main/Aligned/3.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/SS_LLkn52Y0.wav ../../MMMO/Main/Raw/Transcript/Full/SS_LLkn52Y0.trs ../../MMMO/Main/Aligned/SS_LLkn52Y0.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/5_E6StQG0ps.wav ../../MMMO/Main/Raw/Transcript/Full/5_E6StQG0ps.trs ../../MMMO/Main/Aligned/5_E6StQG0ps.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/x0UrNKVcSak.wav ../../MMMO/Main/Raw/Transcript/Full/x0UrNKVcSak.trs ../../MMMO/Main/Aligned/x0UrNKVcSak.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/d6hH302o4v8.wav ../../MMMO/Main/Raw/Transcript/Full/d6hH302o4v8.trs ../../MMMO/Main/Aligned/d6hH302o4v8.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/7LT-nZzY3qM.wav ../../MMMO/Main/Raw/Transcript/Full/7LT-nZzY3qM.trs ../../MMMO/Main/Aligned/7LT-nZzY3qM.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/cQte2nml674.wav ../../MMMO/Main/Raw/Transcript/Full/cQte2nml674.trs ../../MMMO/Main/Aligned/cQte2nml674.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/Ci-AH39fi3Y.wav ../../MMMO/Main/Raw/Transcript/Full/Ci-AH39fi3Y.trs ../../MMMO/Main/Aligned/Ci-AH39fi3Y.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/N9Cnv7ZpQfg.wav ../../MMMO/Main/Raw/Transcript/Full/N9Cnv7ZpQfg.trs ../../MMMO/Main/Aligned/N9Cnv7ZpQfg.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/8r6xCUXRw2E.wav ../../MMMO/Main/Raw/Transcript/Full/8r6xCUXRw2E.trs ../../MMMO/Main/Aligned/8r6xCUXRw2E.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/57.wav ../../MMMO/Main/Raw/Transcript/Full/57.trs ../../MMMO/Main/Aligned/57.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/pLTX3ipuDJI.wav ../../MMMO/Main/Raw/Transcript/Full/pLTX3ipuDJI.trs ../../MMMO/Main/Aligned/pLTX3ipuDJI.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/mmqW12d1S8U.wav ../../MMMO/Main/Raw/Transcript/Full/mmqW12d1S8U.trs ../../MMMO/Main/Aligned/mmqW12d1S8U.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/z0krjI3_vlY.wav ../../MMMO/Main/Raw/Transcript/Full/z0krjI3_vlY.trs ../../MMMO/Main/Aligned/z0krjI3_vlY.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/yN4mi10TkiE.wav ../../MMMO/Main/Raw/Transcript/Full/yN4mi10TkiE.trs ../../MMMO/Main/Aligned/yN4mi10TkiE.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/7JsX8y1ysxY.wav ../../MMMO/Main/Raw/Transcript/Full/7JsX8y1ysxY.trs ../../MMMO/Main/Aligned/7JsX8y1ysxY.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/2iD-tVS8NPw.wav ../../MMMO/Main/Raw/Transcript/Full/2iD-tVS8NPw.trs ../../MMMO/Main/Aligned/2iD-tVS8NPw.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/krLgSqwtfsU.wav ../../MMMO/Main/Raw/Transcript/Full/krLgSqwtfsU.trs ../../MMMO/Main/Aligned/krLgSqwtfsU.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/tIrG4oNLFzE.wav ../../MMMO/Main/Raw/Transcript/Full/tIrG4oNLFzE.trs ../../MMMO/Main/Aligned/tIrG4oNLFzE.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/fCgThX4v5yY.wav ../../MMMO/Main/Raw/Transcript/Full/fCgThX4v5yY.trs ../../MMMO/Main/Aligned/fCgThX4v5yY.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/G-xst2euQUc.wav ../../MMMO/Main/Raw/Transcript/Full/G-xst2euQUc.trs ../../MMMO/Main/Aligned/G-xst2euQUc.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/GQRZyNFWF9k.wav ../../MMMO/Main/Raw/Transcript/Full/GQRZyNFWF9k.trs ../../MMMO/Main/Aligned/GQRZyNFWF9k.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/UhUl7-jfDuo.wav ../../MMMO/Main/Raw/Transcript/Full/UhUl7-jfDuo.trs ../../MMMO/Main/Aligned/UhUl7-jfDuo.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/bru1xWJOIvQ.wav ../../MMMO/Main/Raw/Transcript/Full/bru1xWJOIvQ.trs ../../MMMO/Main/Aligned/bru1xWJOIvQ.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/73jzhE8R1TQ.wav ../../MMMO/Main/Raw/Transcript/Full/73jzhE8R1TQ.trs ../../MMMO/Main/Aligned/73jzhE8R1TQ.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/ZIUntPZlLp4.wav ../../MMMO/Main/Raw/Transcript/Full/ZIUntPZlLp4.trs ../../MMMO/Main/Aligned/ZIUntPZlLp4.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/mWXPxxM8Eew.wav ../../MMMO/Main/Raw/Transcript/Full/mWXPxxM8Eew.trs ../../MMMO/Main/Aligned/mWXPxxM8Eew.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/NjDWBX2MONE.wav ../../MMMO/Main/Raw/Transcript/Full/NjDWBX2MONE.trs ../../MMMO/Main/Aligned/NjDWBX2MONE.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/dq3Nf_lMPnE.wav ../../MMMO/Main/Raw/Transcript/Full/dq3Nf_lMPnE.trs ../../MMMO/Main/Aligned/dq3Nf_lMPnE.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/70.wav ../../MMMO/Main/Raw/Transcript/Full/70.trs ../../MMMO/Main/Aligned/70.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/bgMPEzNlczY.wav ../../MMMO/Main/Raw/Transcript/Full/bgMPEzNlczY.trs ../../MMMO/Main/Aligned/bgMPEzNlczY.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/17.wav ../../MMMO/Main/Raw/Transcript/Full/17.trs ../../MMMO/Main/Aligned/17.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/iiK8YX8oH1E.wav ../../MMMO/Main/Raw/Transcript/Full/iiK8YX8oH1E.trs ../../MMMO/Main/Aligned/iiK8YX8oH1E.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/PZ-lDQFboO8.wav ../../MMMO/Main/Raw/Transcript/Full/PZ-lDQFboO8.trs ../../MMMO/Main/Aligned/PZ-lDQFboO8.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/lXPQBPVc5Cw.wav ../../MMMO/Main/Raw/Transcript/Full/lXPQBPVc5Cw.trs ../../MMMO/Main/Aligned/lXPQBPVc5Cw.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/OABxVWlbnw0.wav ../../MMMO/Main/Raw/Transcript/Full/OABxVWlbnw0.trs ../../MMMO/Main/Aligned/OABxVWlbnw0.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/Bfr499ggo-0.wav ../../MMMO/Main/Raw/Transcript/Full/Bfr499ggo-0.trs ../../MMMO/Main/Aligned/Bfr499ggo-0.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/sLyaXDGHl_Q.wav ../../MMMO/Main/Raw/Transcript/Full/sLyaXDGHl_Q.trs ../../MMMO/Main/Aligned/sLyaXDGHl_Q.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/Rj_ra1IXdhY.wav ../../MMMO/Main/Raw/Transcript/Full/Rj_ra1IXdhY.trs ../../MMMO/Main/Aligned/Rj_ra1IXdhY.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/40.wav ../../MMMO/Main/Raw/Transcript/Full/40.trs ../../MMMO/Main/Aligned/40.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/I5y0__X72p0.wav ../../MMMO/Main/Raw/Transcript/Full/I5y0__X72p0.trs ../../MMMO/Main/Aligned/I5y0__X72p0.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/phBUpBr1hSo.wav ../../MMMO/Main/Raw/Transcript/Full/phBUpBr1hSo.trs ../../MMMO/Main/Aligned/phBUpBr1hSo.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/iUBLEfLx_qU.wav ../../MMMO/Main/Raw/Transcript/Full/iUBLEfLx_qU.trs ../../MMMO/Main/Aligned/iUBLEfLx_qU.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/aWC_Wd6dIJw.wav ../../MMMO/Main/Raw/Transcript/Full/aWC_Wd6dIJw.trs ../../MMMO/Main/Aligned/aWC_Wd6dIJw.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/Q7xEufVpGQI.wav ../../MMMO/Main/Raw/Transcript/Full/Q7xEufVpGQI.trs ../../MMMO/Main/Aligned/Q7xEufVpGQI.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/xgSEGbYhMgQ.wav ../../MMMO/Main/Raw/Transcript/Full/xgSEGbYhMgQ.trs ../../MMMO/Main/Aligned/xgSEGbYhMgQ.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/51.wav ../../MMMO/Main/Raw/Transcript/Full/51.trs ../../MMMO/Main/Aligned/51.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/aiEXnCPZubE.wav ../../MMMO/Main/Raw/Transcript/Full/aiEXnCPZubE.trs ../../MMMO/Main/Aligned/aiEXnCPZubE.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/39.wav ../../MMMO/Main/Raw/Transcript/Full/39.trs ../../MMMO/Main/Aligned/39.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/nPWRhXX02rg.wav ../../MMMO/Main/Raw/Transcript/Full/nPWRhXX02rg.trs ../../MMMO/Main/Aligned/nPWRhXX02rg.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/rqOrqug5MZI.wav ../../MMMO/Main/Raw/Transcript/Full/rqOrqug5MZI.trs ../../MMMO/Main/Aligned/rqOrqug5MZI.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/7V7UIVDzCDs.wav ../../MMMO/Main/Raw/Transcript/Full/7V7UIVDzCDs.trs ../../MMMO/Main/Aligned/7V7UIVDzCDs.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/29.wav ../../MMMO/Main/Raw/Transcript/Full/29.trs ../../MMMO/Main/Aligned/29.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/C5dIUwkCPTI.wav ../../MMMO/Main/Raw/Transcript/Full/C5dIUwkCPTI.trs ../../MMMO/Main/Aligned/C5dIUwkCPTI.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/A5rfgIHgdRk.wav ../../MMMO/Main/Raw/Transcript/Full/A5rfgIHgdRk.trs ../../MMMO/Main/Aligned/A5rfgIHgdRk.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/68.wav ../../MMMO/Main/Raw/Transcript/Full/68.trs ../../MMMO/Main/Aligned/68.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/Yh7QPdp-Ogo.wav ../../MMMO/Main/Raw/Transcript/Full/Yh7QPdp-Ogo.trs ../../MMMO/Main/Aligned/Yh7QPdp-Ogo.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/Clx4VXItLTE.wav ../../MMMO/Main/Raw/Transcript/Full/Clx4VXItLTE.trs ../../MMMO/Main/Aligned/Clx4VXItLTE.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/s2DrJU1ucIg.wav ../../MMMO/Main/Raw/Transcript/Full/s2DrJU1ucIg.trs ../../MMMO/Main/Aligned/s2DrJU1ucIg.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/pOc79ta8IvI.wav ../../MMMO/Main/Raw/Transcript/Full/pOc79ta8IvI.trs ../../MMMO/Main/Aligned/pOc79ta8IvI.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/QQO8D_hRj7A.wav ../../MMMO/Main/Raw/Transcript/Full/QQO8D_hRj7A.trs ../../MMMO/Main/Aligned/QQO8D_hRj7A.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/rnaNMUZpvvg.wav ../../MMMO/Main/Raw/Transcript/Full/rnaNMUZpvvg.trs ../../MMMO/Main/Aligned/rnaNMUZpvvg.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/je2mBPA54ec.wav ../../MMMO/Main/Raw/Transcript/Full/je2mBPA54ec.trs ../../MMMO/Main/Aligned/je2mBPA54ec.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/uMvyHrvf8fo.wav ../../MMMO/Main/Raw/Transcript/Full/uMvyHrvf8fo.trs ../../MMMO/Main/Aligned/uMvyHrvf8fo.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/37.wav ../../MMMO/Main/Raw/Transcript/Full/37.trs ../../MMMO/Main/Aligned/37.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/98V9YOBzo3A.wav ../../MMMO/Main/Raw/Transcript/Full/98V9YOBzo3A.trs ../../MMMO/Main/Aligned/98V9YOBzo3A.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/dOo3_fb0g9Y.wav ../../MMMO/Main/Raw/Transcript/Full/dOo3_fb0g9Y.trs ../../MMMO/Main/Aligned/dOo3_fb0g9Y.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/HEsqda8_d0Q.wav ../../MMMO/Main/Raw/Transcript/Full/HEsqda8_d0Q.trs ../../MMMO/Main/Aligned/HEsqda8_d0Q.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/O8j9pjoZwhg.wav ../../MMMO/Main/Raw/Transcript/Full/O8j9pjoZwhg.trs ../../MMMO/Main/Aligned/O8j9pjoZwhg.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/Jkswaaud0hk.wav ../../MMMO/Main/Raw/Transcript/Full/Jkswaaud0hk.trs ../../MMMO/Main/Aligned/Jkswaaud0hk.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/gH88DdnYYZw.wav ../../MMMO/Main/Raw/Transcript/Full/gH88DdnYYZw.trs ../../MMMO/Main/Aligned/gH88DdnYYZw.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/W-Z-Bti05FE.wav ../../MMMO/Main/Raw/Transcript/Full/W-Z-Bti05FE.trs ../../MMMO/Main/Aligned/W-Z-Bti05FE.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/6.wav ../../MMMO/Main/Raw/Transcript/Full/6.trs ../../MMMO/Main/Aligned/6.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/OQvJTdtJ2H4.wav ../../MMMO/Main/Raw/Transcript/Full/OQvJTdtJ2H4.trs ../../MMMO/Main/Aligned/OQvJTdtJ2H4.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/60.wav ../../MMMO/Main/Raw/Transcript/Full/60.trs ../../MMMO/Main/Aligned/60.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/uMz2sdn9IFk.wav ../../MMMO/Main/Raw/Transcript/Full/uMz2sdn9IFk.trs ../../MMMO/Main/Aligned/uMz2sdn9IFk.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/8J62nq8htE4.wav ../../MMMO/Main/Raw/Transcript/Full/8J62nq8htE4.trs ../../MMMO/Main/Aligned/8J62nq8htE4.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/VK1M5EzTPPM.wav ../../MMMO/Main/Raw/Transcript/Full/VK1M5EzTPPM.trs ../../MMMO/Main/Aligned/VK1M5EzTPPM.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/TkubYssog1o.wav ../../MMMO/Main/Raw/Transcript/Full/TkubYssog1o.trs ../../MMMO/Main/Aligned/TkubYssog1o.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/eFsvEXwMB8s.wav ../../MMMO/Main/Raw/Transcript/Full/eFsvEXwMB8s.trs ../../MMMO/Main/Aligned/eFsvEXwMB8s.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/20.wav ../../MMMO/Main/Raw/Transcript/Full/20.trs ../../MMMO/Main/Aligned/20.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/ob23OKe5a9Q.wav ../../MMMO/Main/Raw/Transcript/Full/ob23OKe5a9Q.trs ../../MMMO/Main/Aligned/ob23OKe5a9Q.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/27.wav ../../MMMO/Main/Raw/Transcript/Full/27.trs ../../MMMO/Main/Aligned/27.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/IumbAb8q2dM.wav ../../MMMO/Main/Raw/Transcript/Full/IumbAb8q2dM.trs ../../MMMO/Main/Aligned/IumbAb8q2dM.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/11.wav ../../MMMO/Main/Raw/Transcript/Full/11.trs ../../MMMO/Main/Aligned/11.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/oxXeaqUdKEY.wav ../../MMMO/Main/Raw/Transcript/Full/oxXeaqUdKEY.trs ../../MMMO/Main/Aligned/oxXeaqUdKEY.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/zCQ62cCb-Hk.wav ../../MMMO/Main/Raw/Transcript/Full/zCQ62cCb-Hk.trs ../../MMMO/Main/Aligned/zCQ62cCb-Hk.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/72.wav ../../MMMO/Main/Raw/Transcript/Full/72.trs ../../MMMO/Main/Aligned/72.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/BioHAh1qJAQ.wav ../../MMMO/Main/Raw/Transcript/Full/BioHAh1qJAQ.trs ../../MMMO/Main/Aligned/BioHAh1qJAQ.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/yvsjCA6Y5Fc.wav ../../MMMO/Main/Raw/Transcript/Full/yvsjCA6Y5Fc.trs ../../MMMO/Main/Aligned/yvsjCA6Y5Fc.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/U9zK-dxNQ1c.wav ../../MMMO/Main/Raw/Transcript/Full/U9zK-dxNQ1c.trs ../../MMMO/Main/Aligned/U9zK-dxNQ1c.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/Iu2PFX3z_1s.wav ../../MMMO/Main/Raw/Transcript/Full/Iu2PFX3z_1s.trs ../../MMMO/Main/Aligned/Iu2PFX3z_1s.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/61.wav ../../MMMO/Main/Raw/Transcript/Full/61.trs ../../MMMO/Main/Aligned/61.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/YVGYxPE8CUU.wav ../../MMMO/Main/Raw/Transcript/Full/YVGYxPE8CUU.trs ../../MMMO/Main/Aligned/YVGYxPE8CUU.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/5E94G7gCAcc.wav ../../MMMO/Main/Raw/Transcript/Full/5E94G7gCAcc.trs ../../MMMO/Main/Aligned/5E94G7gCAcc.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/EF7DAx_9rf0.wav ../../MMMO/Main/Raw/Transcript/Full/EF7DAx_9rf0.trs ../../MMMO/Main/Aligned/EF7DAx_9rf0.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/wVVZW7XQnq8.wav ../../MMMO/Main/Raw/Transcript/Full/wVVZW7XQnq8.trs ../../MMMO/Main/Aligned/wVVZW7XQnq8.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/ZAIRrfG22O0.wav ../../MMMO/Main/Raw/Transcript/Full/ZAIRrfG22O0.trs ../../MMMO/Main/Aligned/ZAIRrfG22O0.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/nTbx24Z1FRg.wav ../../MMMO/Main/Raw/Transcript/Full/nTbx24Z1FRg.trs ../../MMMO/Main/Aligned/nTbx24Z1FRg.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/_QZSjLjsrEg.wav ../../MMMO/Main/Raw/Transcript/Full/_QZSjLjsrEg.trs ../../MMMO/Main/Aligned/_QZSjLjsrEg.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/qygYRKHvXdw.wav ../../MMMO/Main/Raw/Transcript/Full/qygYRKHvXdw.trs ../../MMMO/Main/Aligned/qygYRKHvXdw.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/POKffnXeBds.wav ../../MMMO/Main/Raw/Transcript/Full/POKffnXeBds.trs ../../MMMO/Main/Aligned/POKffnXeBds.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/R1ULYT8eBzk.wav ../../MMMO/Main/Raw/Transcript/Full/R1ULYT8eBzk.trs ../../MMMO/Main/Aligned/R1ULYT8eBzk.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/QN9ZIUWUXsY.wav ../../MMMO/Main/Raw/Transcript/Full/QN9ZIUWUXsY.trs ../../MMMO/Main/Aligned/QN9ZIUWUXsY.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/G6GlGvlkxAQ.wav ../../MMMO/Main/Raw/Transcript/Full/G6GlGvlkxAQ.trs ../../MMMO/Main/Aligned/G6GlGvlkxAQ.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/TZrLMil-SJk.wav ../../MMMO/Main/Raw/Transcript/Full/TZrLMil-SJk.trs ../../MMMO/Main/Aligned/TZrLMil-SJk.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/YaVc0EHrigI.wav ../../MMMO/Main/Raw/Transcript/Full/YaVc0EHrigI.trs ../../MMMO/Main/Aligned/YaVc0EHrigI.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/6Egk_28TtTM.wav ../../MMMO/Main/Raw/Transcript/Full/6Egk_28TtTM.trs ../../MMMO/Main/Aligned/6Egk_28TtTM.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/d3_k5Xpfmik.wav ../../MMMO/Main/Raw/Transcript/Full/d3_k5Xpfmik.trs ../../MMMO/Main/Aligned/d3_k5Xpfmik.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/1.wav ../../MMMO/Main/Raw/Transcript/Full/1.trs ../../MMMO/Main/Aligned/1.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/43.wav ../../MMMO/Main/Raw/Transcript/Full/43.trs ../../MMMO/Main/Aligned/43.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/85HdAGEd4OQ.wav ../../MMMO/Main/Raw/Transcript/Full/85HdAGEd4OQ.trs ../../MMMO/Main/Aligned/85HdAGEd4OQ.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/5.wav ../../MMMO/Main/Raw/Transcript/Full/5.trs ../../MMMO/Main/Aligned/5.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/OmOfkY9-_Y0.wav ../../MMMO/Main/Raw/Transcript/Full/OmOfkY9-_Y0.trs ../../MMMO/Main/Aligned/OmOfkY9-_Y0.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/_dI--eQ6qVU.wav ../../MMMO/Main/Raw/Transcript/Full/_dI--eQ6qVU.trs ../../MMMO/Main/Aligned/_dI--eQ6qVU.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/0TsJQCrfOHE.wav ../../MMMO/Main/Raw/Transcript/Full/0TsJQCrfOHE.trs ../../MMMO/Main/Aligned/0TsJQCrfOHE.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/bOL9jKpeJRs.wav ../../MMMO/Main/Raw/Transcript/Full/bOL9jKpeJRs.trs ../../MMMO/Main/Aligned/bOL9jKpeJRs.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/l7-P4TfTWM4.wav ../../MMMO/Main/Raw/Transcript/Full/l7-P4TfTWM4.trs ../../MMMO/Main/Aligned/l7-P4TfTWM4.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/65.wav ../../MMMO/Main/Raw/Transcript/Full/65.trs ../../MMMO/Main/Aligned/65.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/XzrO6l6uFDk.wav ../../MMMO/Main/Raw/Transcript/Full/XzrO6l6uFDk.trs ../../MMMO/Main/Aligned/XzrO6l6uFDk.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/rHyN6tc7caA.wav ../../MMMO/Main/Raw/Transcript/Full/rHyN6tc7caA.trs ../../MMMO/Main/Aligned/rHyN6tc7caA.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/JT0Z8insTVU.wav ../../MMMO/Main/Raw/Transcript/Full/JT0Z8insTVU.trs ../../MMMO/Main/Aligned/JT0Z8insTVU.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/0qk_SvrlHGk.wav ../../MMMO/Main/Raw/Transcript/Full/0qk_SvrlHGk.trs ../../MMMO/Main/Aligned/0qk_SvrlHGk.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/18.wav ../../MMMO/Main/Raw/Transcript/Full/18.trs ../../MMMO/Main/Aligned/18.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/yy-YrwEwk7E.wav ../../MMMO/Main/Raw/Transcript/Full/yy-YrwEwk7E.trs ../../MMMO/Main/Aligned/yy-YrwEwk7E.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/cW1FSBF59ik.wav ../../MMMO/Main/Raw/Transcript/Full/cW1FSBF59ik.trs ../../MMMO/Main/Aligned/cW1FSBF59ik.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/DMgGajEGvlo.wav ../../MMMO/Main/Raw/Transcript/Full/DMgGajEGvlo.trs ../../MMMO/Main/Aligned/DMgGajEGvlo.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/nbWiPyCm4g0.wav ../../MMMO/Main/Raw/Transcript/Full/nbWiPyCm4g0.trs ../../MMMO/Main/Aligned/nbWiPyCm4g0.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/38.wav ../../MMMO/Main/Raw/Transcript/Full/38.trs ../../MMMO/Main/Aligned/38.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/OtBXNcAL_lE.wav ../../MMMO/Main/Raw/Transcript/Full/OtBXNcAL_lE.trs ../../MMMO/Main/Aligned/OtBXNcAL_lE.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/8OtFthrtaJM.wav ../../MMMO/Main/Raw/Transcript/Full/8OtFthrtaJM.trs ../../MMMO/Main/Aligned/8OtFthrtaJM.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/BkE_y9qNydA.wav ../../MMMO/Main/Raw/Transcript/Full/BkE_y9qNydA.trs ../../MMMO/Main/Aligned/BkE_y9qNydA.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/tStelxIAHjw.wav ../../MMMO/Main/Raw/Transcript/Full/tStelxIAHjw.trs ../../MMMO/Main/Aligned/tStelxIAHjw.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/DmiXxw9PoMU.wav ../../MMMO/Main/Raw/Transcript/Full/DmiXxw9PoMU.trs ../../MMMO/Main/Aligned/DmiXxw9PoMU.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/VbQk4H8hgr0.wav ../../MMMO/Main/Raw/Transcript/Full/VbQk4H8hgr0.trs ../../MMMO/Main/Aligned/VbQk4H8hgr0.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/cap26yHB7mI.wav ../../MMMO/Main/Raw/Transcript/Full/cap26yHB7mI.trs ../../MMMO/Main/Aligned/cap26yHB7mI.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/8qrpnFRGt2A.wav ../../MMMO/Main/Raw/Transcript/Full/8qrpnFRGt2A.trs ../../MMMO/Main/Aligned/8qrpnFRGt2A.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/_fmcuzRjWDQ.wav ../../MMMO/Main/Raw/Transcript/Full/_fmcuzRjWDQ.trs ../../MMMO/Main/Aligned/_fmcuzRjWDQ.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/8.wav ../../MMMO/Main/Raw/Transcript/Full/8.trs ../../MMMO/Main/Aligned/8.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/xwwq0kqXrho.wav ../../MMMO/Main/Raw/Transcript/Full/xwwq0kqXrho.trs ../../MMMO/Main/Aligned/xwwq0kqXrho.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/-R7DCLNXNNA.wav ../../MMMO/Main/Raw/Transcript/Full/-R7DCLNXNNA.trs ../../MMMO/Main/Aligned/-R7DCLNXNNA.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/yMQ9WeIZTNU.wav ../../MMMO/Main/Raw/Transcript/Full/yMQ9WeIZTNU.trs ../../MMMO/Main/Aligned/yMQ9WeIZTNU.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/GCF_QAv7g7c.wav ../../MMMO/Main/Raw/Transcript/Full/GCF_QAv7g7c.trs ../../MMMO/Main/Aligned/GCF_QAv7g7c.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/Oz06ZWiO20M.wav ../../MMMO/Main/Raw/Transcript/Full/Oz06ZWiO20M.trs ../../MMMO/Main/Aligned/Oz06ZWiO20M.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/54.wav ../../MMMO/Main/Raw/Transcript/Full/54.trs ../../MMMO/Main/Aligned/54.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/9c67fiY0wGQ.wav ../../MMMO/Main/Raw/Transcript/Full/9c67fiY0wGQ.trs ../../MMMO/Main/Aligned/9c67fiY0wGQ.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/8d-gEyoeBzc.wav ../../MMMO/Main/Raw/Transcript/Full/8d-gEyoeBzc.trs ../../MMMO/Main/Aligned/8d-gEyoeBzc.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/5W7Z1C_fDaE.wav ../../MMMO/Main/Raw/Transcript/Full/5W7Z1C_fDaE.trs ../../MMMO/Main/Aligned/5W7Z1C_fDaE.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/3lZjpX5cvqg.wav ../../MMMO/Main/Raw/Transcript/Full/3lZjpX5cvqg.trs ../../MMMO/Main/Aligned/3lZjpX5cvqg.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/Af8D0E4ZXaw.wav ../../MMMO/Main/Raw/Transcript/Full/Af8D0E4ZXaw.trs ../../MMMO/Main/Aligned/Af8D0E4ZXaw.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/bWX_P8aapgs.wav ../../MMMO/Main/Raw/Transcript/Full/bWX_P8aapgs.trs ../../MMMO/Main/Aligned/bWX_P8aapgs.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/QJQoxCs-6n8.wav ../../MMMO/Main/Raw/Transcript/Full/QJQoxCs-6n8.trs ../../MMMO/Main/Aligned/QJQoxCs-6n8.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/K5PFf7mrF9k.wav ../../MMMO/Main/Raw/Transcript/Full/K5PFf7mrF9k.trs ../../MMMO/Main/Aligned/K5PFf7mrF9k.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/Hpg5HaBJ8Ko.wav ../../MMMO/Main/Raw/Transcript/Full/Hpg5HaBJ8Ko.trs ../../MMMO/Main/Aligned/Hpg5HaBJ8Ko.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/r9hae_IksMg.wav ../../MMMO/Main/Raw/Transcript/Full/r9hae_IksMg.trs ../../MMMO/Main/Aligned/r9hae_IksMg.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/O7rTOLiCaUI.wav ../../MMMO/Main/Raw/Transcript/Full/O7rTOLiCaUI.trs ../../MMMO/Main/Aligned/O7rTOLiCaUI.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/IX-GT3TeLfE.wav ../../MMMO/Main/Raw/Transcript/Full/IX-GT3TeLfE.trs ../../MMMO/Main/Aligned/IX-GT3TeLfE.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/k_3UKY7ySdI.wav ../../MMMO/Main/Raw/Transcript/Full/k_3UKY7ySdI.trs ../../MMMO/Main/Aligned/k_3UKY7ySdI.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/36.wav ../../MMMO/Main/Raw/Transcript/Full/36.trs ../../MMMO/Main/Aligned/36.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/yeuRo5qknmE.wav ../../MMMO/Main/Raw/Transcript/Full/yeuRo5qknmE.trs ../../MMMO/Main/Aligned/yeuRo5qknmE.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/4aFrrDB9xjc.wav ../../MMMO/Main/Raw/Transcript/Full/4aFrrDB9xjc.trs ../../MMMO/Main/Aligned/4aFrrDB9xjc.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/9T9Hf74oK10.wav ../../MMMO/Main/Raw/Transcript/Full/9T9Hf74oK10.trs ../../MMMO/Main/Aligned/9T9Hf74oK10.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/J04uUJnlaJA.wav ../../MMMO/Main/Raw/Transcript/Full/J04uUJnlaJA.trs ../../MMMO/Main/Aligned/J04uUJnlaJA.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/UnKGQU0PrN0.wav ../../MMMO/Main/Raw/Transcript/Full/UnKGQU0PrN0.trs ../../MMMO/Main/Aligned/UnKGQU0PrN0.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/25.wav ../../MMMO/Main/Raw/Transcript/Full/25.trs ../../MMMO/Main/Aligned/25.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/R3AlkrN21Qk.wav ../../MMMO/Main/Raw/Transcript/Full/R3AlkrN21Qk.trs ../../MMMO/Main/Aligned/R3AlkrN21Qk.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/MLal-t_vJPM.wav ../../MMMO/Main/Raw/Transcript/Full/MLal-t_vJPM.trs ../../MMMO/Main/Aligned/MLal-t_vJPM.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/YA0WBp9Mieg.wav ../../MMMO/Main/Raw/Transcript/Full/YA0WBp9Mieg.trs ../../MMMO/Main/Aligned/YA0WBp9Mieg.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/P0H8L7KiAS8.wav ../../MMMO/Main/Raw/Transcript/Full/P0H8L7KiAS8.trs ../../MMMO/Main/Aligned/P0H8L7KiAS8.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/Qr1Ca94K55A.wav ../../MMMO/Main/Raw/Transcript/Full/Qr1Ca94K55A.trs ../../MMMO/Main/Aligned/Qr1Ca94K55A.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/71.wav ../../MMMO/Main/Raw/Transcript/Full/71.trs ../../MMMO/Main/Aligned/71.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/raikYkfoNPg.wav ../../MMMO/Main/Raw/Transcript/Full/raikYkfoNPg.trs ../../MMMO/Main/Aligned/raikYkfoNPg.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/l7Q_5COZle4.wav ../../MMMO/Main/Raw/Transcript/Full/l7Q_5COZle4.trs ../../MMMO/Main/Aligned/l7Q_5COZle4.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/44.wav ../../MMMO/Main/Raw/Transcript/Full/44.trs ../../MMMO/Main/Aligned/44.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/67.wav ../../MMMO/Main/Raw/Transcript/Full/67.trs ../../MMMO/Main/Aligned/67.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/53.wav ../../MMMO/Main/Raw/Transcript/Full/53.trs ../../MMMO/Main/Aligned/53.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/zlRgUpoh-G0.wav ../../MMMO/Main/Raw/Transcript/Full/zlRgUpoh-G0.trs ../../MMMO/Main/Aligned/zlRgUpoh-G0.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/Fi-9vuPZzcY.wav ../../MMMO/Main/Raw/Transcript/Full/Fi-9vuPZzcY.trs ../../MMMO/Main/Aligned/Fi-9vuPZzcY.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/WKA5OygbEKI.wav ../../MMMO/Main/Raw/Transcript/Full/WKA5OygbEKI.trs ../../MMMO/Main/Aligned/WKA5OygbEKI.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/cTUTUEAOIHI.wav ../../MMMO/Main/Raw/Transcript/Full/cTUTUEAOIHI.trs ../../MMMO/Main/Aligned/cTUTUEAOIHI.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/u_aprAlkiaA.wav ../../MMMO/Main/Raw/Transcript/Full/u_aprAlkiaA.trs ../../MMMO/Main/Aligned/u_aprAlkiaA.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/pq9gQOlR6y0.wav ../../MMMO/Main/Raw/Transcript/Full/pq9gQOlR6y0.trs ../../MMMO/Main/Aligned/pq9gQOlR6y0.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/mJibXwzTDeI.wav ../../MMMO/Main/Raw/Transcript/Full/mJibXwzTDeI.trs ../../MMMO/Main/Aligned/mJibXwzTDeI.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/bgS3yUy0hAA.wav ../../MMMO/Main/Raw/Transcript/Full/bgS3yUy0hAA.trs ../../MMMO/Main/Aligned/bgS3yUy0hAA.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/XhBIYUZcPrs.wav ../../MMMO/Main/Raw/Transcript/Full/XhBIYUZcPrs.trs ../../MMMO/Main/Aligned/XhBIYUZcPrs.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/k5Y_838nuGo.wav ../../MMMO/Main/Raw/Transcript/Full/k5Y_838nuGo.trs ../../MMMO/Main/Aligned/k5Y_838nuGo.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/Ffgw6D0STiA.wav ../../MMMO/Main/Raw/Transcript/Full/Ffgw6D0STiA.trs ../../MMMO/Main/Aligned/Ffgw6D0STiA.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/aRg1nnFU1e0.wav ../../MMMO/Main/Raw/Transcript/Full/aRg1nnFU1e0.trs ../../MMMO/Main/Aligned/aRg1nnFU1e0.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/iZRuxVRTUSs.wav ../../MMMO/Main/Raw/Transcript/Full/iZRuxVRTUSs.trs ../../MMMO/Main/Aligned/iZRuxVRTUSs.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/14.wav ../../MMMO/Main/Raw/Transcript/Full/14.trs ../../MMMO/Main/Aligned/14.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/icmObdHF94k.wav ../../MMMO/Main/Raw/Transcript/Full/icmObdHF94k.trs ../../MMMO/Main/Aligned/icmObdHF94k.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/3n7uo-9DRIE.wav ../../MMMO/Main/Raw/Transcript/Full/3n7uo-9DRIE.trs ../../MMMO/Main/Aligned/3n7uo-9DRIE.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/vvZ4IcEtiZc.wav ../../MMMO/Main/Raw/Transcript/Full/vvZ4IcEtiZc.trs ../../MMMO/Main/Aligned/vvZ4IcEtiZc.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/f9O3YtZ2VfI.wav ../../MMMO/Main/Raw/Transcript/Full/f9O3YtZ2VfI.trs ../../MMMO/Main/Aligned/f9O3YtZ2VfI.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/26.wav ../../MMMO/Main/Raw/Transcript/Full/26.trs ../../MMMO/Main/Aligned/26.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/34.wav ../../MMMO/Main/Raw/Transcript/Full/34.trs ../../MMMO/Main/Aligned/34.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/ucWV2vdrhwo.wav ../../MMMO/Main/Raw/Transcript/Full/ucWV2vdrhwo.trs ../../MMMO/Main/Aligned/ucWV2vdrhwo.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/12.wav ../../MMMO/Main/Raw/Transcript/Full/12.trs ../../MMMO/Main/Aligned/12.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/v7Nz_V_lVwU.wav ../../MMMO/Main/Raw/Transcript/Full/v7Nz_V_lVwU.trs ../../MMMO/Main/Aligned/v7Nz_V_lVwU.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/GKKISlttugE.wav ../../MMMO/Main/Raw/Transcript/Full/GKKISlttugE.trs ../../MMMO/Main/Aligned/GKKISlttugE.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/9QfL2NE_qZk.wav ../../MMMO/Main/Raw/Transcript/Full/9QfL2NE_qZk.trs ../../MMMO/Main/Aligned/9QfL2NE_qZk.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/YAeN9o2nndU.wav ../../MMMO/Main/Raw/Transcript/Full/YAeN9o2nndU.trs ../../MMMO/Main/Aligned/YAeN9o2nndU.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/1DmNV9C1hbY.wav ../../MMMO/Main/Raw/Transcript/Full/1DmNV9C1hbY.trs ../../MMMO/Main/Aligned/1DmNV9C1hbY.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/9J25DZhivz8.wav ../../MMMO/Main/Raw/Transcript/Full/9J25DZhivz8.trs ../../MMMO/Main/Aligned/9J25DZhivz8.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/nWFS9jBBGwk.wav ../../MMMO/Main/Raw/Transcript/Full/nWFS9jBBGwk.trs ../../MMMO/Main/Aligned/nWFS9jBBGwk.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/gTIy_03JPWY.wav ../../MMMO/Main/Raw/Transcript/Full/gTIy_03JPWY.trs ../../MMMO/Main/Aligned/gTIy_03JPWY.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/24.wav ../../MMMO/Main/Raw/Transcript/Full/24.trs ../../MMMO/Main/Aligned/24.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/Nzq88NnDkEk.wav ../../MMMO/Main/Raw/Transcript/Full/Nzq88NnDkEk.trs ../../MMMO/Main/Aligned/Nzq88NnDkEk.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/TvyZBvOMOTc.wav ../../MMMO/Main/Raw/Transcript/Full/TvyZBvOMOTc.trs ../../MMMO/Main/Aligned/TvyZBvOMOTc.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/wMbj6ajWbic.wav ../../MMMO/Main/Raw/Transcript/Full/wMbj6ajWbic.trs ../../MMMO/Main/Aligned/wMbj6ajWbic.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/etzxEpPuc6I.wav ../../MMMO/Main/Raw/Transcript/Full/etzxEpPuc6I.trs ../../MMMO/Main/Aligned/etzxEpPuc6I.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/VJWcvJiQwXs.wav ../../MMMO/Main/Raw/Transcript/Full/VJWcvJiQwXs.trs ../../MMMO/Main/Aligned/VJWcvJiQwXs.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/aehUajsljvA.wav ../../MMMO/Main/Raw/Transcript/Full/aehUajsljvA.trs ../../MMMO/Main/Aligned/aehUajsljvA.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/draehCZv508.wav ../../MMMO/Main/Raw/Transcript/Full/draehCZv508.trs ../../MMMO/Main/Aligned/draehCZv508.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/45.wav ../../MMMO/Main/Raw/Transcript/Full/45.trs ../../MMMO/Main/Aligned/45.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/NGE84bLEj94.wav ../../MMMO/Main/Raw/Transcript/Full/NGE84bLEj94.trs ../../MMMO/Main/Aligned/NGE84bLEj94.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/ttjTGFpmr10.wav ../../MMMO/Main/Raw/Transcript/Full/ttjTGFpmr10.trs ../../MMMO/Main/Aligned/ttjTGFpmr10.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/5cxlONQEN6A.wav ../../MMMO/Main/Raw/Transcript/Full/5cxlONQEN6A.trs ../../MMMO/Main/Aligned/5cxlONQEN6A.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/hsPGrIZlD5E.wav ../../MMMO/Main/Raw/Transcript/Full/hsPGrIZlD5E.trs ../../MMMO/Main/Aligned/hsPGrIZlD5E.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/GWuJjcEuzt8.wav ../../MMMO/Main/Raw/Transcript/Full/GWuJjcEuzt8.trs ../../MMMO/Main/Aligned/GWuJjcEuzt8.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/76.wav ../../MMMO/Main/Raw/Transcript/Full/76.trs ../../MMMO/Main/Aligned/76.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/IbjU9uF3sQY.wav ../../MMMO/Main/Raw/Transcript/Full/IbjU9uF3sQY.trs ../../MMMO/Main/Aligned/IbjU9uF3sQY.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/vyB00TXsimI.wav ../../MMMO/Main/Raw/Transcript/Full/vyB00TXsimI.trs ../../MMMO/Main/Aligned/vyB00TXsimI.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/uIu7UMBM9Tc.wav ../../MMMO/Main/Raw/Transcript/Full/uIu7UMBM9Tc.trs ../../MMMO/Main/Aligned/uIu7UMBM9Tc.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/PI_w1W7EKeA.wav ../../MMMO/Main/Raw/Transcript/Full/PI_w1W7EKeA.trs ../../MMMO/Main/Aligned/PI_w1W7EKeA.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/75.wav ../../MMMO/Main/Raw/Transcript/Full/75.trs ../../MMMO/Main/Aligned/75.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/58.wav ../../MMMO/Main/Raw/Transcript/Full/58.trs ../../MMMO/Main/Aligned/58.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/cM3Yna7AavY.wav ../../MMMO/Main/Raw/Transcript/Full/cM3Yna7AavY.trs ../../MMMO/Main/Aligned/cM3Yna7AavY.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/65IIbYmEL48.wav ../../MMMO/Main/Raw/Transcript/Full/65IIbYmEL48.trs ../../MMMO/Main/Aligned/65IIbYmEL48.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/vkGIqFlRHvA.wav ../../MMMO/Main/Raw/Transcript/Full/vkGIqFlRHvA.trs ../../MMMO/Main/Aligned/vkGIqFlRHvA.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/3WiiT0xTV6A.wav ../../MMMO/Main/Raw/Transcript/Full/3WiiT0xTV6A.trs ../../MMMO/Main/Aligned/3WiiT0xTV6A.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/NTLDmbbftVQ.wav ../../MMMO/Main/Raw/Transcript/Full/NTLDmbbftVQ.trs ../../MMMO/Main/Aligned/NTLDmbbftVQ.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/MEY6oTxvE40.wav ../../MMMO/Main/Raw/Transcript/Full/MEY6oTxvE40.trs ../../MMMO/Main/Aligned/MEY6oTxvE40.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/nzpVDcQ0ywM.wav ../../MMMO/Main/Raw/Transcript/Full/nzpVDcQ0ywM.trs ../../MMMO/Main/Aligned/nzpVDcQ0ywM.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/yoy3XaaLFRE.wav ../../MMMO/Main/Raw/Transcript/Full/yoy3XaaLFRE.trs ../../MMMO/Main/Aligned/yoy3XaaLFRE.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/n7_QUDNKDnY.wav ../../MMMO/Main/Raw/Transcript/Full/n7_QUDNKDnY.trs ../../MMMO/Main/Aligned/n7_QUDNKDnY.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/naKrZkoAtNY.wav ../../MMMO/Main/Raw/Transcript/Full/naKrZkoAtNY.trs ../../MMMO/Main/Aligned/naKrZkoAtNY.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/pfvIxMDrgdg.wav ../../MMMO/Main/Raw/Transcript/Full/pfvIxMDrgdg.trs ../../MMMO/Main/Aligned/pfvIxMDrgdg.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/1ELLHkV7VPA.wav ../../MMMO/Main/Raw/Transcript/Full/1ELLHkV7VPA.trs ../../MMMO/Main/Aligned/1ELLHkV7VPA.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/GxlcmCEkOms.wav ../../MMMO/Main/Raw/Transcript/Full/GxlcmCEkOms.trs ../../MMMO/Main/Aligned/GxlcmCEkOms.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/bvLlb-M3UXU.wav ../../MMMO/Main/Raw/Transcript/Full/bvLlb-M3UXU.trs ../../MMMO/Main/Aligned/bvLlb-M3UXU.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/_3zvxaeOT3s.wav ../../MMMO/Main/Raw/Transcript/Full/_3zvxaeOT3s.trs ../../MMMO/Main/Aligned/_3zvxaeOT3s.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/liB4PuaxWPY.wav ../../MMMO/Main/Raw/Transcript/Full/liB4PuaxWPY.trs ../../MMMO/Main/Aligned/liB4PuaxWPY.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/KUr8byJFYbs.wav ../../MMMO/Main/Raw/Transcript/Full/KUr8byJFYbs.trs ../../MMMO/Main/Aligned/KUr8byJFYbs.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/55.wav ../../MMMO/Main/Raw/Transcript/Full/55.trs ../../MMMO/Main/Aligned/55.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/X3j2zQgwYgE.wav ../../MMMO/Main/Raw/Transcript/Full/X3j2zQgwYgE.trs ../../MMMO/Main/Aligned/X3j2zQgwYgE.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/eLKc5gIddmk.wav ../../MMMO/Main/Raw/Transcript/Full/eLKc5gIddmk.trs ../../MMMO/Main/Aligned/eLKc5gIddmk.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/2BtpNib7JwA.wav ../../MMMO/Main/Raw/Transcript/Full/2BtpNib7JwA.trs ../../MMMO/Main/Aligned/2BtpNib7JwA.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/wqjpkmWj2p8.wav ../../MMMO/Main/Raw/Transcript/Full/wqjpkmWj2p8.trs ../../MMMO/Main/Aligned/wqjpkmWj2p8.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/mCuxbdT5a6Q.wav ../../MMMO/Main/Raw/Transcript/Full/mCuxbdT5a6Q.trs ../../MMMO/Main/Aligned/mCuxbdT5a6Q.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/JHlVnV1i9RY.wav ../../MMMO/Main/Raw/Transcript/Full/JHlVnV1i9RY.trs ../../MMMO/Main/Aligned/JHlVnV1i9RY.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/sat7DOLpdTo.wav ../../MMMO/Main/Raw/Transcript/Full/sat7DOLpdTo.trs ../../MMMO/Main/Aligned/sat7DOLpdTo.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/LSi-o-IrDMs.wav ../../MMMO/Main/Raw/Transcript/Full/LSi-o-IrDMs.trs ../../MMMO/Main/Aligned/LSi-o-IrDMs.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/KkFT4icNuE0.wav ../../MMMO/Main/Raw/Transcript/Full/KkFT4icNuE0.trs ../../MMMO/Main/Aligned/KkFT4icNuE0.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/pmxxVJwfFmM.wav ../../MMMO/Main/Raw/Transcript/Full/pmxxVJwfFmM.trs ../../MMMO/Main/Aligned/pmxxVJwfFmM.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/2WbFZRt0Tic.wav ../../MMMO/Main/Raw/Transcript/Full/2WbFZRt0Tic.trs ../../MMMO/Main/Aligned/2WbFZRt0Tic.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/pKSWt7jJI9I.wav ../../MMMO/Main/Raw/Transcript/Full/pKSWt7jJI9I.trs ../../MMMO/Main/Aligned/pKSWt7jJI9I.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/xzJNL1TvsA8.wav ../../MMMO/Main/Raw/Transcript/Full/xzJNL1TvsA8.trs ../../MMMO/Main/Aligned/xzJNL1TvsA8.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/MHGXm9UyMRs.wav ../../MMMO/Main/Raw/Transcript/Full/MHGXm9UyMRs.trs ../../MMMO/Main/Aligned/MHGXm9UyMRs.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/Jxu8mc0ODcA.wav ../../MMMO/Main/Raw/Transcript/Full/Jxu8mc0ODcA.trs ../../MMMO/Main/Aligned/Jxu8mc0ODcA.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/wmJttySG-U8.wav ../../MMMO/Main/Raw/Transcript/Full/wmJttySG-U8.trs ../../MMMO/Main/Aligned/wmJttySG-U8.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/uV5FY1b6nNQ.wav ../../MMMO/Main/Raw/Transcript/Full/uV5FY1b6nNQ.trs ../../MMMO/Main/Aligned/uV5FY1b6nNQ.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/2w1AufHoWUQ.wav ../../MMMO/Main/Raw/Transcript/Full/2w1AufHoWUQ.trs ../../MMMO/Main/Aligned/2w1AufHoWUQ.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/z67UATsmKTE.wav ../../MMMO/Main/Raw/Transcript/Full/z67UATsmKTE.trs ../../MMMO/Main/Aligned/z67UATsmKTE.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/30.wav ../../MMMO/Main/Raw/Transcript/Full/30.trs ../../MMMO/Main/Aligned/30.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/JxNQ1ojXZ-I.wav ../../MMMO/Main/Raw/Transcript/Full/JxNQ1ojXZ-I.trs ../../MMMO/Main/Aligned/JxNQ1ojXZ-I.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/52.wav ../../MMMO/Main/Raw/Transcript/Full/52.trs ../../MMMO/Main/Aligned/52.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/W8NXH0Djyww.wav ../../MMMO/Main/Raw/Transcript/Full/W8NXH0Djyww.trs ../../MMMO/Main/Aligned/W8NXH0Djyww.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/BXuRRbG0Ugk.wav ../../MMMO/Main/Raw/Transcript/Full/BXuRRbG0Ugk.trs ../../MMMO/Main/Aligned/BXuRRbG0Ugk.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/FmfeRJi7yUs.wav ../../MMMO/Main/Raw/Transcript/Full/FmfeRJi7yUs.trs ../../MMMO/Main/Aligned/FmfeRJi7yUs.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/u_xo52w47Bo.wav ../../MMMO/Main/Raw/Transcript/Full/u_xo52w47Bo.trs ../../MMMO/Main/Aligned/u_xo52w47Bo.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/8NPNOlEvnrM.wav ../../MMMO/Main/Raw/Transcript/Full/8NPNOlEvnrM.trs ../../MMMO/Main/Aligned/8NPNOlEvnrM.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/EYc2UIkjRD0.wav ../../MMMO/Main/Raw/Transcript/Full/EYc2UIkjRD0.trs ../../MMMO/Main/Aligned/EYc2UIkjRD0.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/yDtzw_Y-7RU.wav ../../MMMO/Main/Raw/Transcript/Full/yDtzw_Y-7RU.trs ../../MMMO/Main/Aligned/yDtzw_Y-7RU.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/Sqr0AcuoNnk.wav ../../MMMO/Main/Raw/Transcript/Full/Sqr0AcuoNnk.trs ../../MMMO/Main/Aligned/Sqr0AcuoNnk.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/eCPRCjzaOC4.wav ../../MMMO/Main/Raw/Transcript/Full/eCPRCjzaOC4.trs ../../MMMO/Main/Aligned/eCPRCjzaOC4.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/v0zCBqDeKcE.wav ../../MMMO/Main/Raw/Transcript/Full/v0zCBqDeKcE.trs ../../MMMO/Main/Aligned/v0zCBqDeKcE.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/NTZT-v1sj1o.wav ../../MMMO/Main/Raw/Transcript/Full/NTZT-v1sj1o.trs ../../MMMO/Main/Aligned/NTZT-v1sj1o.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/f_3zHJ6BP0E.wav ../../MMMO/Main/Raw/Transcript/Full/f_3zHJ6BP0E.trs ../../MMMO/Main/Aligned/f_3zHJ6BP0E.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/ZUXBRvtny7o.wav ../../MMMO/Main/Raw/Transcript/Full/ZUXBRvtny7o.trs ../../MMMO/Main/Aligned/ZUXBRvtny7o.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/03bSnISJMiM.wav ../../MMMO/Main/Raw/Transcript/Full/03bSnISJMiM.trs ../../MMMO/Main/Aligned/03bSnISJMiM.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/Vj1wYRQjB-o.wav ../../MMMO/Main/Raw/Transcript/Full/Vj1wYRQjB-o.trs ../../MMMO/Main/Aligned/Vj1wYRQjB-o.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/Dg_0XKD0Mf4.wav ../../MMMO/Main/Raw/Transcript/Full/Dg_0XKD0Mf4.trs ../../MMMO/Main/Aligned/Dg_0XKD0Mf4.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/OclHlLnPqWQ.wav ../../MMMO/Main/Raw/Transcript/Full/OclHlLnPqWQ.trs ../../MMMO/Main/Aligned/OclHlLnPqWQ.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/mlxOdQDt_pQ.wav ../../MMMO/Main/Raw/Transcript/Full/mlxOdQDt_pQ.trs ../../MMMO/Main/Aligned/mlxOdQDt_pQ.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/4.wav ../../MMMO/Main/Raw/Transcript/Full/4.trs ../../MMMO/Main/Aligned/4.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/73.wav ../../MMMO/Main/Raw/Transcript/Full/73.trs ../../MMMO/Main/Aligned/73.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/RxnpX2DG0ig.wav ../../MMMO/Main/Raw/Transcript/Full/RxnpX2DG0ig.trs ../../MMMO/Main/Aligned/RxnpX2DG0ig.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/2.wav ../../MMMO/Main/Raw/Transcript/Full/2.trs ../../MMMO/Main/Aligned/2.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/zhpQhgha_KU.wav ../../MMMO/Main/Raw/Transcript/Full/zhpQhgha_KU.trs ../../MMMO/Main/Aligned/zhpQhgha_KU.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/0h-zjBukYpk.wav ../../MMMO/Main/Raw/Transcript/Full/0h-zjBukYpk.trs ../../MMMO/Main/Aligned/0h-zjBukYpk.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/qwmZ9LwVzf0.wav ../../MMMO/Main/Raw/Transcript/Full/qwmZ9LwVzf0.trs ../../MMMO/Main/Aligned/qwmZ9LwVzf0.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/mkUZZQ5VKTI.wav ../../MMMO/Main/Raw/Transcript/Full/mkUZZQ5VKTI.trs ../../MMMO/Main/Aligned/mkUZZQ5VKTI.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/74.wav ../../MMMO/Main/Raw/Transcript/Full/74.trs ../../MMMO/Main/Aligned/74.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/6_0THN4chvY.wav ../../MMMO/Main/Raw/Transcript/Full/6_0THN4chvY.trs ../../MMMO/Main/Aligned/6_0THN4chvY.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/E0rULsDkloA.wav ../../MMMO/Main/Raw/Transcript/Full/E0rULsDkloA.trs ../../MMMO/Main/Aligned/E0rULsDkloA.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/9.wav ../../MMMO/Main/Raw/Transcript/Full/9.trs ../../MMMO/Main/Aligned/9.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/n0HYg3uS3b4.wav ../../MMMO/Main/Raw/Transcript/Full/n0HYg3uS3b4.trs ../../MMMO/Main/Aligned/n0HYg3uS3b4.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/aG9ZvQEaBBE.wav ../../MMMO/Main/Raw/Transcript/Full/aG9ZvQEaBBE.trs ../../MMMO/Main/Aligned/aG9ZvQEaBBE.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/o3YQ4Gr-ErM.wav ../../MMMO/Main/Raw/Transcript/Full/o3YQ4Gr-ErM.trs ../../MMMO/Main/Aligned/o3YQ4Gr-ErM.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/bV85tXYX9-c.wav ../../MMMO/Main/Raw/Transcript/Full/bV85tXYX9-c.trs ../../MMMO/Main/Aligned/bV85tXYX9-c.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/XSUxtUy0ZU4.wav ../../MMMO/Main/Raw/Transcript/Full/XSUxtUy0ZU4.trs ../../MMMO/Main/Aligned/XSUxtUy0ZU4.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/MlcMKwxz9uE.wav ../../MMMO/Main/Raw/Transcript/Full/MlcMKwxz9uE.trs ../../MMMO/Main/Aligned/MlcMKwxz9uE.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/whEWe6PDjSY.wav ../../MMMO/Main/Raw/Transcript/Full/whEWe6PDjSY.trs ../../MMMO/Main/Aligned/whEWe6PDjSY.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/Ayo5SYUzQYo.wav ../../MMMO/Main/Raw/Transcript/Full/Ayo5SYUzQYo.trs ../../MMMO/Main/Aligned/Ayo5SYUzQYo.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/f_pcplsH_V0.wav ../../MMMO/Main/Raw/Transcript/Full/f_pcplsH_V0.trs ../../MMMO/Main/Aligned/f_pcplsH_V0.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/fSSJEdaQcwM.wav ../../MMMO/Main/Raw/Transcript/Full/fSSJEdaQcwM.trs ../../MMMO/Main/Aligned/fSSJEdaQcwM.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/bhwu4TwUedc.wav ../../MMMO/Main/Raw/Transcript/Full/bhwu4TwUedc.trs ../../MMMO/Main/Aligned/bhwu4TwUedc.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/V7kwW5RkOxk.wav ../../MMMO/Main/Raw/Transcript/Full/V7kwW5RkOxk.trs ../../MMMO/Main/Aligned/V7kwW5RkOxk.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/T3Ev40yduDU.wav ../../MMMO/Main/Raw/Transcript/Full/T3Ev40yduDU.trs ../../MMMO/Main/Aligned/T3Ev40yduDU.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/jUzDDGyPkXU.wav ../../MMMO/Main/Raw/Transcript/Full/jUzDDGyPkXU.trs ../../MMMO/Main/Aligned/jUzDDGyPkXU.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/VCslbP0mgZI.wav ../../MMMO/Main/Raw/Transcript/Full/VCslbP0mgZI.trs ../../MMMO/Main/Aligned/VCslbP0mgZI.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/c5xsKMxpXnc.wav ../../MMMO/Main/Raw/Transcript/Full/c5xsKMxpXnc.trs ../../MMMO/Main/Aligned/c5xsKMxpXnc.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/UFi8lHMMABU.wav ../../MMMO/Main/Raw/Transcript/Full/UFi8lHMMABU.trs ../../MMMO/Main/Aligned/UFi8lHMMABU.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/OeeS1DCZicQ.wav ../../MMMO/Main/Raw/Transcript/Full/OeeS1DCZicQ.trs ../../MMMO/Main/Aligned/OeeS1DCZicQ.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/tmZoasNr4rU.wav ../../MMMO/Main/Raw/Transcript/Full/tmZoasNr4rU.trs ../../MMMO/Main/Aligned/tmZoasNr4rU.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/vvfOjfYCdEY.wav ../../MMMO/Main/Raw/Transcript/Full/vvfOjfYCdEY.trs ../../MMMO/Main/Aligned/vvfOjfYCdEY.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/cXypl4FnoZo.wav ../../MMMO/Main/Raw/Transcript/Full/cXypl4FnoZo.trs ../../MMMO/Main/Aligned/cXypl4FnoZo.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/9qR7uwkblbs.wav ../../MMMO/Main/Raw/Transcript/Full/9qR7uwkblbs.trs ../../MMMO/Main/Aligned/9qR7uwkblbs.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/42.wav ../../MMMO/Main/Raw/Transcript/Full/42.trs ../../MMMO/Main/Aligned/42.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/atnd_PF-Lbs.wav ../../MMMO/Main/Raw/Transcript/Full/atnd_PF-Lbs.trs ../../MMMO/Main/Aligned/atnd_PF-Lbs.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/WS9EvCmOAI0.wav ../../MMMO/Main/Raw/Transcript/Full/WS9EvCmOAI0.trs ../../MMMO/Main/Aligned/WS9EvCmOAI0.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/kRCynfnYtw8.wav ../../MMMO/Main/Raw/Transcript/Full/kRCynfnYtw8.trs ../../MMMO/Main/Aligned/kRCynfnYtw8.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/tyJmZlV3ZKA.wav ../../MMMO/Main/Raw/Transcript/Full/tyJmZlV3ZKA.trs ../../MMMO/Main/Aligned/tyJmZlV3ZKA.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/mq3Y_oPQzmQ.wav ../../MMMO/Main/Raw/Transcript/Full/mq3Y_oPQzmQ.trs ../../MMMO/Main/Aligned/mq3Y_oPQzmQ.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/8MzKpvcYtnU.wav ../../MMMO/Main/Raw/Transcript/Full/8MzKpvcYtnU.trs ../../MMMO/Main/Aligned/8MzKpvcYtnU.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/5zZg3J4vQ30.wav ../../MMMO/Main/Raw/Transcript/Full/5zZg3J4vQ30.trs ../../MMMO/Main/Aligned/5zZg3J4vQ30.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/c7UH_rxdZv4.wav ../../MMMO/Main/Raw/Transcript/Full/c7UH_rxdZv4.trs ../../MMMO/Main/Aligned/c7UH_rxdZv4.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/fvVhgmXxadc.wav ../../MMMO/Main/Raw/Transcript/Full/fvVhgmXxadc.trs ../../MMMO/Main/Aligned/fvVhgmXxadc.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/19.wav ../../MMMO/Main/Raw/Transcript/Full/19.trs ../../MMMO/Main/Aligned/19.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/5kclWCa9bys.wav ../../MMMO/Main/Raw/Transcript/Full/5kclWCa9bys.trs ../../MMMO/Main/Aligned/5kclWCa9bys.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/ZmCQp52pmwA.wav ../../MMMO/Main/Raw/Transcript/Full/ZmCQp52pmwA.trs ../../MMMO/Main/Aligned/ZmCQp52pmwA.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/FuR4VwKrCU0.wav ../../MMMO/Main/Raw/Transcript/Full/FuR4VwKrCU0.trs ../../MMMO/Main/Aligned/FuR4VwKrCU0.json
sudo python align.py ../../MMMO/Main/Raw/Audio/Full/Njd1F0vZSm4.wav ../../MMMO/Main/Raw/Transcript/Full/Njd1F0vZSm4.trs ../../MMMO/Main/Aligned/Njd1F0vZSm4.json
