sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/1iG0909rllw.wav ../../MOSI/Raw/Transcript/Full/1iG0909rllw.textonly ../../MOSI/Aligned/1iG0909rllw.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/2WGyTLYerpo.wav ../../MOSI/Raw/Transcript/Full/2WGyTLYerpo.textonly ../../MOSI/Aligned/2WGyTLYerpo.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/d6hH302o4v8.wav ../../MOSI/Raw/Transcript/Full/d6hH302o4v8.textonly ../../MOSI/Aligned/d6hH302o4v8.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/Ci-AH39fi3Y.wav ../../MOSI/Raw/Transcript/Full/Ci-AH39fi3Y.textonly ../../MOSI/Aligned/Ci-AH39fi3Y.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/pLTX3ipuDJI.wav ../../MOSI/Raw/Transcript/Full/pLTX3ipuDJI.textonly ../../MOSI/Aligned/pLTX3ipuDJI.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/BI97DNYfe5I.wav ../../MOSI/Raw/Transcript/Full/BI97DNYfe5I.textonly ../../MOSI/Aligned/BI97DNYfe5I.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/7JsX8y1ysxY.wav ../../MOSI/Raw/Transcript/Full/7JsX8y1ysxY.textonly ../../MOSI/Aligned/7JsX8y1ysxY.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/2iD-tVS8NPw.wav ../../MOSI/Raw/Transcript/Full/2iD-tVS8NPw.textonly ../../MOSI/Aligned/2iD-tVS8NPw.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/tIrG4oNLFzE.wav ../../MOSI/Raw/Transcript/Full/tIrG4oNLFzE.textonly ../../MOSI/Aligned/tIrG4oNLFzE.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/G-xst2euQUc.wav ../../MOSI/Raw/Transcript/Full/G-xst2euQUc.textonly ../../MOSI/Aligned/G-xst2euQUc.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/73jzhE8R1TQ.wav ../../MOSI/Raw/Transcript/Full/73jzhE8R1TQ.textonly ../../MOSI/Aligned/73jzhE8R1TQ.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/dq3Nf_lMPnE.wav ../../MOSI/Raw/Transcript/Full/dq3Nf_lMPnE.textonly ../../MOSI/Aligned/dq3Nf_lMPnE.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/iiK8YX8oH1E.wav ../../MOSI/Raw/Transcript/Full/iiK8YX8oH1E.textonly ../../MOSI/Aligned/iiK8YX8oH1E.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/PZ-lDQFboO8.wav ../../MOSI/Raw/Transcript/Full/PZ-lDQFboO8.textonly ../../MOSI/Aligned/PZ-lDQFboO8.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/lXPQBPVc5Cw.wav ../../MOSI/Raw/Transcript/Full/lXPQBPVc5Cw.textonly ../../MOSI/Aligned/lXPQBPVc5Cw.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/Bfr499ggo-0.wav ../../MOSI/Raw/Transcript/Full/Bfr499ggo-0.textonly ../../MOSI/Aligned/Bfr499ggo-0.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/I5y0__X72p0.wav ../../MOSI/Raw/Transcript/Full/I5y0__X72p0.textonly ../../MOSI/Aligned/I5y0__X72p0.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/phBUpBr1hSo.wav ../../MOSI/Raw/Transcript/Full/phBUpBr1hSo.textonly ../../MOSI/Aligned/phBUpBr1hSo.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/aiEXnCPZubE.wav ../../MOSI/Raw/Transcript/Full/aiEXnCPZubE.textonly ../../MOSI/Aligned/aiEXnCPZubE.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/Clx4VXItLTE.wav ../../MOSI/Raw/Transcript/Full/Clx4VXItLTE.textonly ../../MOSI/Aligned/Clx4VXItLTE.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/rnaNMUZpvvg.wav ../../MOSI/Raw/Transcript/Full/rnaNMUZpvvg.textonly ../../MOSI/Aligned/rnaNMUZpvvg.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/HEsqda8_d0Q.wav ../../MOSI/Raw/Transcript/Full/HEsqda8_d0Q.textonly ../../MOSI/Aligned/HEsqda8_d0Q.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/Jkswaaud0hk.wav ../../MOSI/Raw/Transcript/Full/Jkswaaud0hk.textonly ../../MOSI/Aligned/Jkswaaud0hk.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/OQvJTdtJ2H4.wav ../../MOSI/Raw/Transcript/Full/OQvJTdtJ2H4.textonly ../../MOSI/Aligned/OQvJTdtJ2H4.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/ob23OKe5a9Q.wav ../../MOSI/Raw/Transcript/Full/ob23OKe5a9Q.textonly ../../MOSI/Aligned/ob23OKe5a9Q.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/IumbAb8q2dM.wav ../../MOSI/Raw/Transcript/Full/IumbAb8q2dM.textonly ../../MOSI/Aligned/IumbAb8q2dM.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/BioHAh1qJAQ.wav ../../MOSI/Raw/Transcript/Full/BioHAh1qJAQ.textonly ../../MOSI/Aligned/BioHAh1qJAQ.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/yvsjCA6Y5Fc.wav ../../MOSI/Raw/Transcript/Full/yvsjCA6Y5Fc.textonly ../../MOSI/Aligned/yvsjCA6Y5Fc.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/Iu2PFX3z_1s.wav ../../MOSI/Raw/Transcript/Full/Iu2PFX3z_1s.textonly ../../MOSI/Aligned/Iu2PFX3z_1s.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/ZAIRrfG22O0.wav ../../MOSI/Raw/Transcript/Full/ZAIRrfG22O0.textonly ../../MOSI/Aligned/ZAIRrfG22O0.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/POKffnXeBds.wav ../../MOSI/Raw/Transcript/Full/POKffnXeBds.textonly ../../MOSI/Aligned/POKffnXeBds.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/QN9ZIUWUXsY.wav ../../MOSI/Raw/Transcript/Full/QN9ZIUWUXsY.textonly ../../MOSI/Aligned/QN9ZIUWUXsY.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/G6GlGvlkxAQ.wav ../../MOSI/Raw/Transcript/Full/G6GlGvlkxAQ.textonly ../../MOSI/Aligned/G6GlGvlkxAQ.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/6Egk_28TtTM.wav ../../MOSI/Raw/Transcript/Full/6Egk_28TtTM.textonly ../../MOSI/Aligned/6Egk_28TtTM.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/d3_k5Xpfmik.wav ../../MOSI/Raw/Transcript/Full/d3_k5Xpfmik.textonly ../../MOSI/Aligned/d3_k5Xpfmik.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/_dI--eQ6qVU.wav ../../MOSI/Raw/Transcript/Full/_dI--eQ6qVU.textonly ../../MOSI/Aligned/_dI--eQ6qVU.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/bOL9jKpeJRs.wav ../../MOSI/Raw/Transcript/Full/bOL9jKpeJRs.textonly ../../MOSI/Aligned/bOL9jKpeJRs.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/cW1FSBF59ik.wav ../../MOSI/Raw/Transcript/Full/cW1FSBF59ik.textonly ../../MOSI/Aligned/cW1FSBF59ik.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/nbWiPyCm4g0.wav ../../MOSI/Raw/Transcript/Full/nbWiPyCm4g0.textonly ../../MOSI/Aligned/nbWiPyCm4g0.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/OtBXNcAL_lE.wav ../../MOSI/Raw/Transcript/Full/OtBXNcAL_lE.textonly ../../MOSI/Aligned/OtBXNcAL_lE.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/8OtFthrtaJM.wav ../../MOSI/Raw/Transcript/Full/8OtFthrtaJM.textonly ../../MOSI/Aligned/8OtFthrtaJM.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/tStelxIAHjw.wav ../../MOSI/Raw/Transcript/Full/tStelxIAHjw.textonly ../../MOSI/Aligned/tStelxIAHjw.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/VbQk4H8hgr0.wav ../../MOSI/Raw/Transcript/Full/VbQk4H8hgr0.textonly ../../MOSI/Aligned/VbQk4H8hgr0.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/8qrpnFRGt2A.wav ../../MOSI/Raw/Transcript/Full/8qrpnFRGt2A.textonly ../../MOSI/Aligned/8qrpnFRGt2A.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/Oz06ZWiO20M.wav ../../MOSI/Raw/Transcript/Full/Oz06ZWiO20M.textonly ../../MOSI/Aligned/Oz06ZWiO20M.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/9c67fiY0wGQ.wav ../../MOSI/Raw/Transcript/Full/9c67fiY0wGQ.textonly ../../MOSI/Aligned/9c67fiY0wGQ.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/8d-gEyoeBzc.wav ../../MOSI/Raw/Transcript/Full/8d-gEyoeBzc.textonly ../../MOSI/Aligned/8d-gEyoeBzc.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/5W7Z1C_fDaE.wav ../../MOSI/Raw/Transcript/Full/5W7Z1C_fDaE.textonly ../../MOSI/Aligned/5W7Z1C_fDaE.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/Af8D0E4ZXaw.wav ../../MOSI/Raw/Transcript/Full/Af8D0E4ZXaw.textonly ../../MOSI/Aligned/Af8D0E4ZXaw.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/9T9Hf74oK10.wav ../../MOSI/Raw/Transcript/Full/9T9Hf74oK10.textonly ../../MOSI/Aligned/9T9Hf74oK10.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/MLal-t_vJPM.wav ../../MOSI/Raw/Transcript/Full/MLal-t_vJPM.textonly ../../MOSI/Aligned/MLal-t_vJPM.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/Qr1Ca94K55A.wav ../../MOSI/Raw/Transcript/Full/Qr1Ca94K55A.textonly ../../MOSI/Aligned/Qr1Ca94K55A.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/WKA5OygbEKI.wav ../../MOSI/Raw/Transcript/Full/WKA5OygbEKI.textonly ../../MOSI/Aligned/WKA5OygbEKI.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/BvYR0L6f2Ig.wav ../../MOSI/Raw/Transcript/Full/BvYR0L6f2Ig.textonly ../../MOSI/Aligned/BvYR0L6f2Ig.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/k5Y_838nuGo.wav ../../MOSI/Raw/Transcript/Full/k5Y_838nuGo.textonly ../../MOSI/Aligned/k5Y_838nuGo.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/vvZ4IcEtiZc.wav ../../MOSI/Raw/Transcript/Full/vvZ4IcEtiZc.textonly ../../MOSI/Aligned/vvZ4IcEtiZc.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/f9O3YtZ2VfI.wav ../../MOSI/Raw/Transcript/Full/f9O3YtZ2VfI.textonly ../../MOSI/Aligned/f9O3YtZ2VfI.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/1DmNV9C1hbY.wav ../../MOSI/Raw/Transcript/Full/1DmNV9C1hbY.textonly ../../MOSI/Aligned/1DmNV9C1hbY.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/9J25DZhivz8.wav ../../MOSI/Raw/Transcript/Full/9J25DZhivz8.textonly ../../MOSI/Aligned/9J25DZhivz8.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/Nzq88NnDkEk.wav ../../MOSI/Raw/Transcript/Full/Nzq88NnDkEk.textonly ../../MOSI/Aligned/Nzq88NnDkEk.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/TvyZBvOMOTc.wav ../../MOSI/Raw/Transcript/Full/TvyZBvOMOTc.textonly ../../MOSI/Aligned/TvyZBvOMOTc.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/wMbj6ajWbic.wav ../../MOSI/Raw/Transcript/Full/wMbj6ajWbic.textonly ../../MOSI/Aligned/wMbj6ajWbic.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/etzxEpPuc6I.wav ../../MOSI/Raw/Transcript/Full/etzxEpPuc6I.textonly ../../MOSI/Aligned/etzxEpPuc6I.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/GWuJjcEuzt8.wav ../../MOSI/Raw/Transcript/Full/GWuJjcEuzt8.textonly ../../MOSI/Aligned/GWuJjcEuzt8.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/vyB00TXsimI.wav ../../MOSI/Raw/Transcript/Full/vyB00TXsimI.textonly ../../MOSI/Aligned/vyB00TXsimI.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/cM3Yna7AavY.wav ../../MOSI/Raw/Transcript/Full/cM3Yna7AavY.textonly ../../MOSI/Aligned/cM3Yna7AavY.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/nzpVDcQ0ywM.wav ../../MOSI/Raw/Transcript/Full/nzpVDcQ0ywM.textonly ../../MOSI/Aligned/nzpVDcQ0ywM.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/bvLlb-M3UXU.wav ../../MOSI/Raw/Transcript/Full/bvLlb-M3UXU.textonly ../../MOSI/Aligned/bvLlb-M3UXU.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/X3j2zQgwYgE.wav ../../MOSI/Raw/Transcript/Full/X3j2zQgwYgE.textonly ../../MOSI/Aligned/X3j2zQgwYgE.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/LSi-o-IrDMs.wav ../../MOSI/Raw/Transcript/Full/LSi-o-IrDMs.textonly ../../MOSI/Aligned/LSi-o-IrDMs.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/W8NXH0Djyww.wav ../../MOSI/Raw/Transcript/Full/W8NXH0Djyww.textonly ../../MOSI/Aligned/W8NXH0Djyww.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/BXuRRbG0Ugk.wav ../../MOSI/Raw/Transcript/Full/BXuRRbG0Ugk.textonly ../../MOSI/Aligned/BXuRRbG0Ugk.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/yDtzw_Y-7RU.wav ../../MOSI/Raw/Transcript/Full/yDtzw_Y-7RU.textonly ../../MOSI/Aligned/yDtzw_Y-7RU.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/Sqr0AcuoNnk.wav ../../MOSI/Raw/Transcript/Full/Sqr0AcuoNnk.textonly ../../MOSI/Aligned/Sqr0AcuoNnk.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/v0zCBqDeKcE.wav ../../MOSI/Raw/Transcript/Full/v0zCBqDeKcE.textonly ../../MOSI/Aligned/v0zCBqDeKcE.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/ZUXBRvtny7o.wav ../../MOSI/Raw/Transcript/Full/ZUXBRvtny7o.textonly ../../MOSI/Aligned/ZUXBRvtny7o.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/03bSnISJMiM.wav ../../MOSI/Raw/Transcript/Full/03bSnISJMiM.textonly ../../MOSI/Aligned/03bSnISJMiM.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/Vj1wYRQjB-o.wav ../../MOSI/Raw/Transcript/Full/Vj1wYRQjB-o.textonly ../../MOSI/Aligned/Vj1wYRQjB-o.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/Dg_0XKD0Mf4.wav ../../MOSI/Raw/Transcript/Full/Dg_0XKD0Mf4.textonly ../../MOSI/Aligned/Dg_0XKD0Mf4.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/zhpQhgha_KU.wav ../../MOSI/Raw/Transcript/Full/zhpQhgha_KU.textonly ../../MOSI/Aligned/zhpQhgha_KU.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/0h-zjBukYpk.wav ../../MOSI/Raw/Transcript/Full/0h-zjBukYpk.textonly ../../MOSI/Aligned/0h-zjBukYpk.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/6_0THN4chvY.wav ../../MOSI/Raw/Transcript/Full/6_0THN4chvY.textonly ../../MOSI/Aligned/6_0THN4chvY.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/f_pcplsH_V0.wav ../../MOSI/Raw/Transcript/Full/f_pcplsH_V0.textonly ../../MOSI/Aligned/f_pcplsH_V0.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/jUzDDGyPkXU.wav ../../MOSI/Raw/Transcript/Full/jUzDDGyPkXU.textonly ../../MOSI/Aligned/jUzDDGyPkXU.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/VCslbP0mgZI.wav ../../MOSI/Raw/Transcript/Full/VCslbP0mgZI.textonly ../../MOSI/Aligned/VCslbP0mgZI.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/c5xsKMxpXnc.wav ../../MOSI/Raw/Transcript/Full/c5xsKMxpXnc.textonly ../../MOSI/Aligned/c5xsKMxpXnc.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/tmZoasNr4rU.wav ../../MOSI/Raw/Transcript/Full/tmZoasNr4rU.textonly ../../MOSI/Aligned/tmZoasNr4rU.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/cXypl4FnoZo.wav ../../MOSI/Raw/Transcript/Full/cXypl4FnoZo.textonly ../../MOSI/Aligned/cXypl4FnoZo.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/9qR7uwkblbs.wav ../../MOSI/Raw/Transcript/Full/9qR7uwkblbs.textonly ../../MOSI/Aligned/9qR7uwkblbs.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/atnd_PF-Lbs.wav ../../MOSI/Raw/Transcript/Full/atnd_PF-Lbs.textonly ../../MOSI/Aligned/atnd_PF-Lbs.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/c7UH_rxdZv4.wav ../../MOSI/Raw/Transcript/Full/c7UH_rxdZv4.textonly ../../MOSI/Aligned/c7UH_rxdZv4.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/fvVhgmXxadc.wav ../../MOSI/Raw/Transcript/Full/fvVhgmXxadc.textonly ../../MOSI/Aligned/fvVhgmXxadc.json
sudo python align.py ../../MOSI/Raw/Audio/WAV_16000/Full/Njd1F0vZSm4.wav ../../MOSI/Raw/Transcript/Full/Njd1F0vZSm4.textonly ../../MOSI/Aligned/Njd1F0vZSm4.json
